using System;
using System.Collections.Generic;


using AVcontrol;



namespace JabrAPI.Template
{
    abstract public class IReKey
    {
        protected readonly SecureRandom _random = new(128);  //  Reseed after every 128 generated bytes (min possible amount)
        protected readonly Noisifier _noisifier = new();

        protected readonly List<Byte> _shifts = [0];
        protected Int32 _targetShCount = SecureRandom.LazyInstance.Next(64, 128);
        protected bool _isExportUpToDate = false;



        public ChunkSize ChunkSize { get; set; } = ChunkSize.KByte128;
        public bool KeepOriginalFileExtension = true;

        public Noisifier Noisifier => _noisifier;


        public List<Byte> Shifts => _shifts;
        public Int32 ShCount => _shifts == null ? -1 : _shifts.Count;

        abstract public List<Byte> FinalAlphabet { get; }

        public void UpdateRandomReseedInterval(UInt64 afterGeneratedBytes = 128)
            => _random.UpdateReseedInterval(afterGeneratedBytes);



        abstract public bool ReGenerate();



        abstract public bool ImportFromBinary(Byte[] data, bool throwExceptions = false);
        virtual public Byte[] ExportAsBinary => [];
        public bool ImportFromString(string data, string charsetForImport = DEFAULT.KEY_EXPORT_CHARSET, bool throwExceptions = false)
        {
            try
            {
                Byte[] bytes = [..
                    Numsys.FromDecimalBigInteger<Byte>
                    (
                        Numsys.ToDecimalFromCustomBigInteger(data, charsetForImport),
                        256
                    )   ];
                return ImportFromBinary(bytes);
            }
            catch
            {
                if (throwExceptions) throw;
                return false;
            }
        }
        public string ExportAsString(string charsetForExport = DEFAULT.KEY_EXPORT_CHARSET)
            => Numsys.FromDecimalToCustomBigInteger(
                    Numsys.ToDecimalBigInteger([.. ExportAsBinary], 256),
                    charsetForExport);


        public void GenerateRandomShifts(Int32 count, Byte minVal, Byte maxVal)
        {
            if (count < 0)
            {
                throw new ArgumentOutOfRangeException
                (
                    nameof(count),
                    "count cannot be negative"
                );
            }
            else if (minVal > maxVal)
            {
                throw new ArgumentException
                (
                    "min value cannot be greater than max value",
                    "minVal, maxVal"
                );
            }
            else if (minVal < 0)
            {
                throw new ArgumentOutOfRangeException
                (
                    nameof(minVal),
                    "minVal cannot be negative"
                );
            }

            _isExportUpToDate = false;
            _shifts.Clear();
            if (count == 0)
            {
                _shifts.Add(0);
                return;
            }

            for (var curId = 0; curId < count; curId++)
                _shifts.Add(_random.Next(minVal, maxVal));
        }
        public void GenerateRandomShifts(Byte minVal, Byte maxVal)
            => GenerateRandomShifts(_targetShCount, minVal, maxVal);
    }
}